# Uncomment in case you are behind a HTTP proxy
#ok-http-client:
#  proxy:
#    host: localhost
#    port: 3128

1nce:
  client-id: <your-client-id>
  client-secret: <your-client-secret>
  token-endpoint: "https://portal.1nce.com/management-api/oauth/token"
